services:
    Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand:
        tags:
            - { name: console.command, command: gos:prouter:debug }

    Gos\Bundle\PubSubRouterBundle\Tokenizer\Tokenizer:
        public: false

    Gos\Bundle\PubSubRouterBundle\Tokenizer\TokenizerCacheDecorator:
        public: false
        arguments:
            - '@Gos\Bundle\PubSubRouterBundle\Tokenizer\Tokenizer'
            - '@Gos\Bundle\PubSubRouterBundle\Cache\PhpFileCacheDecorator'

    Gos\Bundle\PubSubRouterBundle\Matcher\Matcher:
        arguments:
            - '@Gos\Bundle\PubSubRouterBundle\Tokenizer\TokenizerCacheDecorator'

    Gos\Bundle\PubSubRouterBundle\Generator\Generator:
        arguments:
            - '@Gos\Bundle\PubSubRouterBundle\Tokenizer\TokenizerCacheDecorator'

    Gos\Bundle\PubSubRouterBundle\Cache\PhpFileCacheDecorator:
        public: false
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'

    Gos\Bundle\PubSubRouterBundle\Loader\YamlFileLoader:
        public: false
        arguments:
            - '@file_locator'
