language: php

php:
    - 7.1
    - 7.2

before_script:
    - composer --prefer-source --dev install

script:
    - phpunit -c phpunit.xml --coverage-text

notifications:
    email:
        - johann_27@hotmail.fr